/** @QspiDxe.c

  Driver for installing BlockIo protocol over QSPI

  Based on NorFlash implementation available in
  ArmPlatformPkg/Drivers/NorFlashDxe/NorFlashDxe.c

  Copyright (c) 2011 - 2014, ARM Ltd. All rights reserved.<BR>
  Copyright (c) 2016 - 2017 NXP.
  All rights reserved.

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD
  License which accompanies this distribution. The full text of the license
  may be found at
http://opensource.org/licenses/bsd-license.php

THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.

 **/

#include <Library/Qspi.h>

STATIC EFI_EVENT mQspiVirtualAddrChangeEvent;
EFI_EVENT EfiExitBootServicesEvent      = (EFI_EVENT)NULL;

//
// Global variable declarations
//
QSPI_FLASH_INSTANCE **mQspiInstances;
UINT32               mQspiDeviceCount;

QSPI_FLASH_INSTANCE  mQspiInstanceTemplate = {
  QSPI_FLASH_SIGNATURE,              // Signature
  NULL,                              // Handle ... NEED TO BE FILLED

  FALSE,                             // Initialized
  NULL,                              // Initialize

  0,                                 // DeviceBaseAddress ... NEED TO BE FILLED
  0,                                 // RegionBaseAddress ... NEED TO BE FILLED
  0,                                 // Size ... NEED TO BE FILLED
  0,                                 // StartLba

  {
    EFI_BLOCK_IO_INTERFACE_REVISION, // Revision
    NULL,                            // Media ... NEED TO BE FILLED
    QspiBlockIoReset,                // Reset
    QspiBlockIoReadBlocks,           // ReadBlocks
    QspiBlockIoWriteBlocks,          // WriteBlocks
    QspiBlockIoFlushBlocks           // FlushBlocks
  },                                 // BlockIoProtocol

  {
    0,                               // MediaId
    FALSE,                           // RemovableMedia
    TRUE,                            // MediaPresent
    FALSE,                           // LogicalPartition
    FALSE,                           // ReadOnly
    FALSE,                           // WriteCaching
    0,                               // BlockSize
    2,                               // IoAlign
    0,                               // Pad
    0                                // LastBlock
  },                                 //Media;

  FALSE,                             // SupportFvb ... NEED TO BE FILLED
  {
    FvbGetAttributes,                // GetAttributes
    FvbSetAttributes,                // SetAttributes
    FvbGetPhysicalAddress,           // GetPhysicalAddress
    FvbGetBlockSize,                 // GetBlockSize
    FvbRead,                         // Read
    FvbWrite,                        // Write
    FvbEraseBlocks,                  // EraseBlocks
    NULL,                            // ParentHandle
  },                                 // FvbProtoccol
  NULL,                              // ShadowBuffer
  // Device path for SemiHosting. It contains our autogenerated Caller ID GUID.
  {
    {
      { HARDWARE_DEVICE_PATH, HW_VENDOR_DP,
        { sizeof (VENDOR_DEVICE_PATH), 0 }
      },
      EFI_CALLER_ID_GUID
    },
    { END_DEVICE_PATH_TYPE,
      END_ENTIRE_DEVICE_PATH_SUBTYPE,
      { sizeof (EFI_DEVICE_PATH_PROTOCOL), 0}
    }
  } // DevicePath
};

  EFI_STATUS
QspiCreateInstance (
    IN UINTN                  QspiDeviceBase,
    IN UINTN                  QspiRegionBase,
    IN UINTN                  QspiSize,
    IN UINT32                 MediaId,
    IN UINT32                 BlockSize,
    IN BOOLEAN                SupportFvb,
    OUT QSPI_FLASH_INSTANCE**  QspiInstance
    )
{
  EFI_STATUS Status;
  QSPI_FLASH_INSTANCE* Instance;

  ASSERT(QspiInstance != NULL);

  Instance = AllocateRuntimeCopyPool (sizeof(QSPI_FLASH_INSTANCE),\
      &mQspiInstanceTemplate);
  if (Instance == NULL) {
    return EFI_OUT_OF_RESOURCES;
  }

  Instance->DeviceBaseAddress = QspiDeviceBase;
  Instance->RegionBaseAddress = QspiRegionBase;
  Instance->Size = QspiSize;

  Instance->BlockIoProtocol.Media = &Instance->Media;
  Instance->Media.MediaId = MediaId;
  Instance->Media.BlockSize = BlockSize;
  Instance->Media.LastBlock = (QspiSize / BlockSize)-1;

  Instance->ShadowBuffer = AllocateRuntimePool (BlockSize);
  if (Instance->ShadowBuffer == NULL) {
    return EFI_OUT_OF_RESOURCES;
  }

  if (SupportFvb) {
    Instance->SupportFvb = TRUE;
    Instance->Initialize = QspiFvbInitialize;

    Status = gBS->InstallMultipleProtocolInterfaces (
        &Instance->Handle,
        &gEfiDevicePathProtocolGuid, &Instance->DevicePath,
        &gEfiBlockIoProtocolGuid,  &Instance->BlockIoProtocol,
        &gEfiFirmwareVolumeBlockProtocolGuid, &Instance->FvbProtocol,
        NULL
        );
    if (EFI_ERROR(Status)) {
      FreePool (Instance);
      return Status;
    }
  } else {
    Instance->Initialized = TRUE;

    Status = gBS->InstallMultipleProtocolInterfaces (
        &Instance->Handle,
        &gEfiDevicePathProtocolGuid, &Instance->DevicePath,
        &gEfiBlockIoProtocolGuid,  &Instance->BlockIoProtocol,
        NULL
        );
    if (EFI_ERROR(Status)) {
      FreePool (Instance);
      return Status;
    }
  }

  *QspiInstance = Instance;
  return Status;
}

  VOID
Swap( UINT8 *Buff, INTN Len)
{
  UINTN Index=0;
  while(Len > 1)
  {
    if(Len >= 8)
    {
      *((UINT64*)(Buff+Index)) = SwapBytes64(*((UINT64*)(Buff+Index)));
      Index += 8;
      Len -=8;
    } else if(Len >= 4)
    {
      *((UINT32*)(Buff+Index)) = SwapBytes32(*((UINT32*)(Buff+Index)));
      Index += 4;
      Len -= 4;
    } else if(Len >= 2)
    {
      *((UINT16*)(Buff+Index)) = SwapBytes16(*((UINT16*)(Buff+Index)));
      Index += 2;
      Len -=2;
    }
  }
}

  EFI_STATUS
QspiRead (
    IN    QSPI_FLASH_INSTANCE            *Instance,
    IN    EFI_LBA                        Lba,
    IN    UINTN                          Offset,
    IN    UINTN                          BufferSizeInBytes,
    OUT   VOID                           *Buffer
    )
{
  EFI_STATUS  Status;
  // Intermediate Bytes needed to copy for alignment
  UINTN       IntBytes = BufferSizeInBytes;
  UINTN       mask = sizeof(UINT64) - 1;
  UINT64      TempRead = 0;
  UINT8       *CopyFrom, *CopyTo;
  UINT8       *pReadData;
  UINTN       BlockSize = Instance->Media.BlockSize;
  UINTN       Counter = 0;

  // The buffer must be valid
  if (Buffer == NULL) {
    return EFI_INVALID_PARAMETER;
  }

  // Return if we have not any byte to read
  if (BufferSizeInBytes == 0) {
    return EFI_SUCCESS;
  }

  if (((Lba * BlockSize) + Offset + BufferSizeInBytes) > Instance->Size) {
    DEBUG ((EFI_D_ERROR, "QspiRead: ERROR - Read will exceed device size.\n"));
    return EFI_INVALID_PARAMETER;
  }

  // First Read bytes to make buffer aligned to Byte Ordering defined in MCR
  if (Offset & mask)
  {
    // Read only as much as necessary, so pick the lower of the two numbers
    if (BufferSizeInBytes < (sizeof(UINT64) - (Offset & mask)) )
      IntBytes = BufferSizeInBytes;
    else
      IntBytes = sizeof(UINT64) - (Offset & mask);
    // Read the first few to get Read buffer aligned
    Status = QspiFlashRead((Offset & ~mask) + GET_BLOCK_OFFSET(Lba),
        sizeof(TempRead),
        &TempRead);
    if (EFI_ERROR (Status))
      return EFI_DEVICE_ERROR;
    else
      TempRead = SwapBytes64(TempRead);
    CopyFrom = (UINT8*)&TempRead;
    CopyFrom += (Offset & mask);
    CopyTo = (UINT8*)Buffer;

    for (Counter=IntBytes; (0 != Counter); Counter--)
      *(CopyTo++) = *(CopyFrom++);

    Offset += IntBytes; // adjust pointers and counter
    BufferSizeInBytes -= IntBytes;
    Buffer += IntBytes;
    if (BufferSizeInBytes == 0)
      return EFI_SUCCESS;
  }

  pReadData = (UINT8*)Buffer;
  IntBytes = (BufferSizeInBytes/8)*8;
  if (IntBytes) {
    // Readout the bytes from Byte Ordered aligned address.
    // Note we can read number of bytes=Byte Ordering defined
    // in MCR in one operation
    Status = QspiFlashRead(Offset + GET_BLOCK_OFFSET(Lba),
        IntBytes,
        pReadData);
    Swap(pReadData,IntBytes);
  }
  Offset += IntBytes;
  BufferSizeInBytes -= IntBytes;
  pReadData += IntBytes;
  if (BufferSizeInBytes == 0)
    return EFI_SUCCESS;

  // Now read bytes that are remaining and are less than Byte Ordering.
  Status = QspiFlashRead(Offset + GET_BLOCK_OFFSET(Lba),
      sizeof(TempRead),
      &TempRead);
  if (EFI_ERROR (Status))
    return EFI_DEVICE_ERROR;
  else
    TempRead = SwapBytes64(TempRead);

  CopyTo = (UINT8*)pReadData;
  CopyFrom = (UINT8*)&TempRead;
  while (BufferSizeInBytes--)
    *(CopyTo++) = *(CopyFrom++);

  return Status;
}

/*
 * The write operation on QSPI flash is changing 1s to 0s
 * Therefore before each QSPI Write we need to erase (make all 1s) QSPI Block
 * However if the data we are trying to write is only clearing (making 1 -> 0)
 * some bits of alrady written data, then we can write that data without erasing
 * entire Block.
 *
 * *DoErase : Boolean, weather we need to erase the block or Not ?
 */
  EFI_STATUS
QspiWriteNoErase (
    IN        QSPI_FLASH_INSTANCE   *Instance,
    IN        EFI_LBA               Lba,
    IN        UINTN                 Offset,
    IN        UINTN                 BufferSizeInBytes,
    IN        UINT8                 *Buffer,
    OUT       BOOLEAN               *DoErase
    )
{
  EFI_STATUS          Status;
  // Intermediate Bytes needed to copy for alignment
  UINTN               IntBytes = BufferSizeInBytes;
  UINTN               mask = sizeof(UINT64) - 1;
  UINT64              TempRead = 0, TempWrite = 0;
  UINT8               *CopyFrom, *CopyTo;
  UINTN               Counter = 0;

  // First Read bytes to make buffer aligned to Byte Ordering
  if (Offset & mask)
  {
    // Read only as much as necessary, so pick the lower of the two numbers
    if (BufferSizeInBytes < (sizeof(UINT64) - (Offset & mask)) )
      IntBytes = BufferSizeInBytes;
    else
      IntBytes = sizeof(UINT64) - (Offset & mask);
    // Read the first few to get Read buffer aligned
    Status = QspiRead(Instance,
        Lba,
        (Offset & ~mask),
        sizeof(TempRead),
        &TempRead);
    if (EFI_ERROR (Status)){
      DEBUG((EFI_D_ERROR, "%a: ERROR - Failed to "
            "Read from Offset 0x%x Status=%d\n",__FUNCTION__,
            (Offset & ~mask) + GET_BLOCK_OFFSET(Lba),Status));
      return Status;
    }

    CopyTo = (UINT8*)&TempRead;
    CopyTo += (Offset & mask);
    CopyFrom = (UINT8*)Buffer;

    for (Counter=IntBytes; (0 != Counter); Counter--)
    {
      // Check to see if we are only changing bits to zero.
      if ((*CopyTo ^ *CopyFrom) & *CopyFrom){
        *DoErase = TRUE;
        return EFI_SUCCESS;
      }
      *(CopyTo++) = *(CopyFrom++);
    }

    TempWrite = SwapBytes64(TempRead);
    Status = QspiFlashWrite ((Offset & ~mask) + GET_BLOCK_OFFSET(Lba),
        sizeof(TempWrite),
        &TempWrite);
    if (EFI_ERROR(Status)) {
      DEBUG((EFI_D_ERROR, "%a: ERROR - Failed to "
            "Write @ Offset 0x%x Status=%d\n",__FUNCTION__,
            (Offset & ~mask) + GET_BLOCK_OFFSET(Lba), Status));
      return Status;
    }

    Offset += IntBytes; // adjust pointers and counter
    BufferSizeInBytes -= IntBytes;
    Buffer += IntBytes;
    if (BufferSizeInBytes == 0){
      *DoErase = FALSE;
      return EFI_SUCCESS;
    }
  }

  IntBytes = (BufferSizeInBytes/sizeof(UINT64))*sizeof(UINT64);
  while (IntBytes) {
    TempWrite = *(UINT64*)Buffer;
    // Readout the bytes from Byte Ordered aligned address.
    // Note we can read number of bytes=Byte Ordering defined
    // in MCR in one operation
    Status = QspiRead(Instance,
        Lba,
        Offset,
        sizeof(TempRead),
        &TempRead);
    if (EFI_ERROR (Status)){
      DEBUG((EFI_D_ERROR, "%a: ERROR - Failed to "
            "Read from Offset 0x%x Status=%d\n",__FUNCTION__,
            Offset + GET_BLOCK_OFFSET(Lba), Status));
      return Status;
    }
    // Check to see if we are only changing bits to zero.
    if ((TempRead ^ TempWrite) & TempWrite){
      *DoErase = TRUE;
      return EFI_SUCCESS;
    }
    TempWrite = SwapBytes64(TempWrite);
    Status = QspiFlashWrite (Offset + GET_BLOCK_OFFSET(Lba),
        sizeof(TempWrite),
        &TempWrite);
    if (EFI_ERROR(Status)) {
      DEBUG((EFI_D_ERROR, "%a: ERROR - Failed to "
            "Write @ Offset 0x%x Status=%d\n",__FUNCTION__,
            Offset + GET_BLOCK_OFFSET(Lba), Status));
      return Status;
    }
    Offset += sizeof(TempWrite);
    BufferSizeInBytes -= sizeof(TempWrite);
    Buffer += sizeof(TempWrite);
    IntBytes -= sizeof(TempWrite);
  }

  if (BufferSizeInBytes == 0){
    *DoErase = FALSE;
    return EFI_SUCCESS;
  }

  // Now read bytes that are remaining and are less than Byte Ordering.
  Status = QspiRead(Instance,
      Lba,
      Offset,
      sizeof(TempRead),
      &TempRead);
  if (EFI_ERROR (Status)){
    DEBUG((EFI_D_ERROR, "%a: ERROR - Failed to "
          "Read from Offset 0x%x Status=%d\n",__FUNCTION__,
          Offset + GET_BLOCK_OFFSET(Lba), Status));
    return Status;
  }

  CopyFrom = (UINT8*)Buffer;
  CopyTo = (UINT8*)&TempRead;
  while (BufferSizeInBytes--)
  {
    // Check to see if we are only changing bits to zero.
    if ((*CopyTo ^ *CopyFrom) & *CopyFrom){
      *DoErase = TRUE;
      return EFI_SUCCESS;
    }
    *(CopyTo++) = *(CopyFrom++);
  }
  TempWrite = SwapBytes64(TempRead);
  Status = QspiFlashWrite (Offset + GET_BLOCK_OFFSET(Lba),
      sizeof(TempWrite),
      &TempWrite);
  if (EFI_ERROR(Status)) {
    DEBUG((EFI_D_ERROR, "%a: ERROR - Failed to "
          "Write @ Offset 0x%x Status=%d\n",__FUNCTION__,
          Offset + GET_BLOCK_OFFSET(Lba), Status));
    return EFI_SUCCESS;
  }
  return EFI_SUCCESS;
}

/*
   Write a full or portion of a block.
   It must not span block boundaries; that is,
   Offset + NumBytes <= Instance->Media.BlockSize.
   */
  EFI_STATUS
QspiWrite (
    IN        QSPI_FLASH_INSTANCE   *Instance,
    IN        EFI_LBA               Lba,
    IN        UINTN                 Offset,
    IN OUT    UINTN                 NumBytes,
    IN        UINT8                 *Buffer
    )
{
  EFI_STATUS               Status = EFI_SUCCESS;
  UINTN                    BlockSize;
  BOOLEAN                  DoErase;

  if (!Instance->Initialized && Instance->Initialize) {
    Instance->Initialize(Instance);
  }

  DEBUG ((DEBUG_BLKIO, "%a(Parameters: Lba=%ld, Offset=0x%x, NumBytes=0x%x, "
        "Buffer @ 0x%08x)\n",__FUNCTION__,
        Lba, Offset, NumBytes, Buffer));

  // The buffer must be valid
  if (Buffer == NULL) {
    return EFI_INVALID_PARAMETER;
  }

  // Detect WriteDisabled state
  if (Instance->Media.ReadOnly == TRUE) {
    DEBUG ((EFI_D_ERROR, "QspiWrite: ERROR - Can not write: "
          "Device is in WriteDisabled state.\n"));
    // It is in WriteDisabled state, return an error right away
    return EFI_ACCESS_DENIED;
  }

  // Cache the block size to avoid de-referencing pointers all the time
  BlockSize = Instance->Media.BlockSize;

  // We must have some bytes to write
  if (NumBytes == 0) {
    DEBUG ((EFI_D_ERROR, "QspiWrite: ERROR - EFI_BAD_BUFFER_SIZE: "
          "(Offset=0x%x + NumBytes=0x%x) > BlockSize=0x%x\n",\
          Offset, NumBytes, BlockSize ));
    return EFI_BAD_BUFFER_SIZE;
  }

  if (((Lba * BlockSize) + Offset + NumBytes) > Instance->Size) {
    DEBUG ((EFI_D_ERROR, "%a: ERROR - Write will exceed device size.\n",
          __FUNCTION__));
    return EFI_INVALID_PARAMETER;
  }

  // Pick 128bytes as a good start for word operations as opposed to erasing the
  // block and writing the data regardless if an erase is really needed.
  // It looks like most individual NV variable writes are smaller than 128bytes.
  if (NumBytes <= 128) {
    // Check to see if we need to erase before programming the data into QSPI.
    // If the destination bits are only changing from 1s to 0s we can 
    // just write. After a block is erased all bits in the block is set to 1.
    // If any byte requires us to erase we just give up and rewrite all of it.
    DoErase = FALSE;
    Status = QspiWriteNoErase(Instance, Lba, Offset, NumBytes, Buffer, 
        &DoErase);
    if (EFI_ERROR (Status)) {
      DEBUG((EFI_D_ERROR, "%a: ERROR - Failed to "
            "Write @ Offset 0x%x Status=%d\n",__FUNCTION__,
            Offset + GET_BLOCK_OFFSET(Lba),Status));
      return Status;
    }
    // Exit if we got here and could write all the data. Otherwise do the
    // Erase-Write cycle.
    if (!DoErase) {
      return EFI_SUCCESS;
    }
  }
  // Check we did get some memory. Buffer is BlockSize.
  if (Instance->ShadowBuffer == NULL) {
    DEBUG ((EFI_D_ERROR, "FvbWrite: ERROR - Buffer not ready\n"));
    return EFI_DEVICE_ERROR;
  }

  // Read QSPI Flash data into shadow buffer
  Status = QspiRead (Instance, Lba, 0, BlockSize, Instance->ShadowBuffer);
  if (EFI_ERROR (Status)) {
    // Return one of the pre-approved error statuses
    return EFI_DEVICE_ERROR;
  }
  // Put the data at the appropriate location inside the buffer area
  CopyMem ((VOID*)((UINTN)Instance->ShadowBuffer + Offset), Buffer, NumBytes);
  Swap((UINT8*)Instance->ShadowBuffer,BlockSize);
  //Erase Block
  Status = QspiFlashErase(GET_BLOCK_OFFSET(Lba), BlockSize);
  if (EFI_ERROR (Status)) {
    // Return one of the pre-approved error statuses
    return EFI_DEVICE_ERROR;
  }
  // Write the modified buffer back to the QspiFlash
  Status = QspiFlashWrite (GET_BLOCK_OFFSET(Lba), BlockSize,
      Instance->ShadowBuffer);
  if (EFI_ERROR (Status)) {
    // Return one of the pre-approved error statuses
    return EFI_DEVICE_ERROR;
  }

  return EFI_SUCCESS;
}

/**
  Shutdown our hardware

  @param[in]  Event     The Event that is being processed
  @param[in]  Context   Event Context
 **/
VOID
  EFIAPI
QspiExitBootServicesEvent (
    IN EFI_EVENT  Event,
    IN VOID       *Context
    )
{
  EFI_HANDLE                    ImageHandle = NULL;
  QspiUnload(ImageHandle);
  QspiFlashFree();
}

/**
  Fixup internal data so that EFI can be call in virtual mode.
  Call the passed in Child Notify event and convert any pointers in
  lib to virtual mode.

  @param[in]    Event   The Event that is being processed
  @param[in]    Context Event Context
 **/
VOID
  EFIAPI
QspiVirtualNotifyEvent (
    IN EFI_EVENT        Event,
    IN VOID             *Context
    )
{
  UINTN Index;

  for (Index = 0; Index < mQspiDeviceCount; Index++) {
    EfiConvertPointer (0x0, (VOID**)&mQspiInstances[Index]->DeviceBaseAddress);
    EfiConvertPointer (0x0, (VOID**)&mQspiInstances[Index]->RegionBaseAddress);

    // Convert BlockIo protocol
    EfiConvertPointer (0x0,
        (VOID**)&mQspiInstances[Index]->BlockIoProtocol.FlushBlocks);
    EfiConvertPointer (0x0,
        (VOID**)&mQspiInstances[Index]->BlockIoProtocol.ReadBlocks);
    EfiConvertPointer (0x0,
        (VOID**)&mQspiInstances[Index]->BlockIoProtocol.Reset);
    EfiConvertPointer (0x0,
        (VOID**)&mQspiInstances[Index]->BlockIoProtocol.WriteBlocks);

    // Convert Fvb
    EfiConvertPointer (0x0,
        (VOID**)&mQspiInstances[Index]->FvbProtocol.EraseBlocks);
    EfiConvertPointer (0x0,
        (VOID**)&mQspiInstances[Index]->FvbProtocol.GetAttributes);
    EfiConvertPointer (0x0,
        (VOID**)&mQspiInstances[Index]->FvbProtocol.GetBlockSize);
    EfiConvertPointer (0x0,
        (VOID**)&mQspiInstances[Index]->FvbProtocol.GetPhysicalAddress);
    EfiConvertPointer (0x0,
        (VOID**)&mQspiInstances[Index]->FvbProtocol.Read);
    EfiConvertPointer (0x0,
        (VOID**)&mQspiInstances[Index]->FvbProtocol.SetAttributes);
    EfiConvertPointer (0x0, (VOID**)&mQspiInstances[Index]->FvbProtocol.Write);

    if (mQspiInstances[Index]->ShadowBuffer != NULL) {
      EfiConvertPointer (0x0, (VOID**)&mQspiInstances[Index]->ShadowBuffer);
    }
    QspiFlashRelocate();
  }
  return;
}

EFI_STATUS
  EFIAPI
QspiInitialize (
    IN EFI_HANDLE         ImageHandle,
    IN EFI_SYSTEM_TABLE   *SystemTable
    )
{
  EFI_STATUS              Status;
  UINT32                  Index;
  QSPI_FLASH_DESCRIPTION*  QspiDevices;
  BOOLEAN                 ContainVariableStorage;

  Status = QspiPlatformInitialization ();
  if (EFI_ERROR(Status)) {
    DEBUG((EFI_D_ERROR,"QspiInitialize: "
          "Fail to initialize Qspi Flash devices\n"));
    return Status;
  }

  Status = QspiPlatformGetDevices (&QspiDevices, &mQspiDeviceCount);
  if (EFI_ERROR(Status)) {
    DEBUG((EFI_D_ERROR,"QspiInitialize: Fail to get Qspi Flash devices\n"));
    return Status;
  }

  Status = QspiPlatformFlashGetAttributes (QspiDevices, mQspiDeviceCount);
  if (EFI_ERROR(Status)) {
    DEBUG((EFI_D_ERROR,"QspiInitialise: Fail to get Qspi device attributes\n"));
    /* System becomes unusable if QSPI flash is not detected */
    ASSERT_EFI_ERROR (Status); 
    return Status;
  }

  mQspiInstances = AllocateRuntimePool (
      sizeof(QSPI_FLASH_INSTANCE*) * mQspiDeviceCount
      );

  for (Index = 0; Index < mQspiDeviceCount; Index++) {
    // Check if this Qspi Flash device contain the variable storage region
    ContainVariableStorage =
      (QspiDevices[Index].RegionBaseAddress <=
       PcdGet64 (PcdFlashNvStorageVariableBase64)) &&
      (PcdGet64 (PcdFlashNvStorageVariableBase64) +
       PcdGet32 (PcdFlashNvStorageVariableSize) <=
       QspiDevices[Index].RegionBaseAddress + QspiDevices[Index].Size);

    Status = QspiCreateInstance (
        QspiDevices[Index].DeviceBaseAddress,
        QspiDevices[Index].RegionBaseAddress,
        QspiDevices[Index].Size,
        Index,
        QspiDevices[Index].BlockSize,
        ContainVariableStorage,
        &mQspiInstances[Index]
        );
    if (EFI_ERROR(Status)) {
      DEBUG((EFI_D_ERROR,"QspiInitialize: "
            "Fail to create instance for Qspi[%d]\n",Index));
    }
    if (FeaturePcdGet(PcdQspiTest) && (TRUE == ContainVariableStorage)) {
      Status = QspiTest(mQspiInstances[Index]);
      if (EFI_ERROR(Status)) {
        DEBUG((EFI_D_ERROR,"QspiInitialize: QspiTest Failed\n"));
        return EFI_DEVICE_ERROR;
      }
    }
  }

  //
  // Register for the virtual address change event
  //
  Status = gBS->CreateEventEx (
      EVT_NOTIFY_SIGNAL,
      TPL_NOTIFY,
      QspiVirtualNotifyEvent,
      NULL,
      &gEfiEventVirtualAddressChangeGuid,
      &mQspiVirtualAddrChangeEvent
      );
  ASSERT_EFI_ERROR (Status);

  return Status;
}

/**
  This is the unload handle for Qspi Controller module.

  Disconnect the driver specified by ImageHandle from all the devices in the
  handle database.
  Uninstall all the protocols installed in the driver entry point.

  @param[in] ImageHandle           The drivers' driver image.

  @retval    EFI_SUCCESS           The image is unloaded.
  @retval    Others                Failed to unload the image.

 **/
EFI_STATUS
  EFIAPI
QspiUnload (
    IN EFI_HANDLE             ImageHandle
    )
{
  EFI_STATUS                            Status;
  EFI_HANDLE                            *DeviceHandleBuffer;
  UINTN                         DeviceHandleCount;

  //
  // Get the list of all Qspi Controller handles in the handle database.
  // If there is an error getting the list, then the unload
  // operation fails.
  //
  Status = gBS->LocateHandleBuffer (
      ByProtocol,
      &gEfiBlockIoProtocolGuid,
      NULL,
      &DeviceHandleCount,
      &DeviceHandleBuffer
      );
  //
  // Free the buffer containing the list of handles from the handle database
  //
  if (DeviceHandleBuffer != NULL) {
    gBS->FreePool (DeviceHandleBuffer);
  }

  return Status;
}
